### PR TITLE
Import Directory.Build.props from parent if present

### PR DESCRIPTION
**Pull request by Alan-Jowett**
Resolve: #151 

Add check if parent folder contains a Directory.Build.props file and import it if present.

### CODE REVIEW

**Review by dthaler — COMMENTED** [review]
I think this solution only works if Directory.Build.props is exactly one level up.
Instead, see the suggestion in https://github.com/microsoft/usersim/issues/151

**Comment by Alan-Jowett** [comment]
@dthaler I am not understanding how the proposed solution in the linked issue would work. My understanding is that msbuild would only load the inner most directory.build.props when processing the vcxproj.

**Review by dthaler — APPROVED** [review]

**Comment by dthaler** [comment]
@Alan-Jowett please rebase

**Comment by Alan-Jowett** [comment]
> @Alan-Jowett please rebase

Rebased.

**Comment by dthaler** [comment]
github reports "Merging can be performed automatically with 1 approving review." even though I approved, so I may not have permissions to be counted.

**Review by nibanks — APPROVED** [review]

**Pull request merged**
